# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 기본 체크아웃
    - name: Checkout
      uses: actions/checkout@v3
    # Gradlew 실행 허용
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
    # JDK 11 세팅
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

     # 환경 변수 설정
    - name: make application.yml
      run: |
       cd ./server/src/main/resources  
       touch ./application.yml 
       echo "${{ secrets.ENV}}" > ./application.yml
      shell: bash

     # Gradle build (Test 제외)
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
              gradle-version: 8.1.1

              arguments: clean build -x test

      # Docker build
    - name: Docker build
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker build -t greennare .
        docker tag greennare todnsp/greennare:${GITHUB_SHA::7}
        docker push todnsp/greennare:${GITHUB_SHA::7}       


      # Deploy
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 35.216.114.50
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        envs: GITHUB_SHA
        script: |
          sudo docker pull todnsp/greennare:${GITHUB_SHA::7}
          sudo docker tag todnsp/greennare:${GITHUB_SHA::7} greennare_spring
          sudo docker-compose up -d
              
              
              
